#!/bin/bash

# Usage: domain-add <admin-email> <domain-name> [<domain-name>]...
ADMIN_EMAIL=$1
DOMAIN_NAMES=${@:2}
CERT_NAME=${DOMAIN_NAMES// /_}
[[ -z "$ADMIN_EMAIL" || -z "$DOMAIN_NAMES" ]] && echo 'Usage: domain-add <admin-email> <domain-name> [<domain-name>]...' && exit 1

# Create nginx server block for the domain linked to certbot certificates
cat > /etc/nginx/conf.d/$CERT_NAME.conf <<EOF
server {
    server_name $DOMAIN_NAMES;
    location / {
        return 404;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    http2 on;
    http3 on;
    quic_retry on;
    ssl_early_data on;
    quic_gso on;

    ssl_certificate /etc/letsencrypt/live/$CERT_NAME/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$CERT_NAME/privkey.pem;

    ssl_session_cache shared:shared_cache:10m;
    ssl_session_timeout 1440m;
    ssl_session_tickets off;
}
EOF

ARGS=()
for DOMAIN in $DOMAIN_NAMES; do
    ARGS+=("-d" "$DOMAIN")
done
certbot certonly --standalone --non-interactive --agree-tos --cert-name $CERT_NAME -m $ADMIN_EMAIL ${ARGS[@]} --deploy-hook "nginx -s reload"
