#!/bin/bash

INPUT_NAME=$1
[[ -z "$INPUT_NAME" ]] && echo 'Usage: domain-remove <cert-name>|<domain-name>' && exit 1

CERT_NAMES=`find /etc/nginx/conf.d -name *$INPUT_NAME*.conf -exec basename {} .conf \;`
[[ -z "$CERT_NAMES" ]] && echo "No matching certificate found for '$INPUT_NAME'" && exit 1

for CERT_NAME in $CERT_NAMES; do
    certbot revoke --non-interactive --delete-after-revoke --cert-name $CERT_NAME
    rm /etc/nginx/conf.d/$CERT_NAME.conf
done

nginx -s reload
